apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 91.7.0
      helm:
        skipCrds: true
        values: |
          crds:
            enabled: false
          grafana:
            service:
              type: LoadBalancer
            persistence:
              enabled: true
              size: 10Gi
            additionalDataSources:
              - name: Loki
                type: loki
                uid: loki
                url: http://loki-gateway.logging.svc.cluster.local
                access: proxy
          prometheus:
            prometheusSpec:
              serviceMonitorSelectorNilUsesHelmValues: false
              podMonitorSelectorNilUsesHelmValues: false
          alertmanager:
            config:
              global:
                resolve_timeout: 5m
          
              route:
                group_by: ['alertname', 'namespace']
                group_wait: 10s
                group_interval: 5m
                repeat_interval: 4h
                receiver: 'webhook-notifications'
          
              receivers:
                - name: 'webhook-notifications'
                  webhook_configs:
                    - url: 'https://webhooksite.net/a4968290-2cbf-4e99-991e-67591646dd09'
                      send_resolved: true
    - repoURL: https://github.com/MaxCurly/kuber-2026-05_project.git
      targetRevision: HEAD
      path: grafana-dashboards/
    - repoURL: https://github.com/MaxCurly/kuber-2026-05_project.git
      targetRevision: HEAD
      path: prometheus-service-monitor/
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
