apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: webhook-config
  namespace: monitoring
  labels:
    alertmanager: main
spec:
  route:
    receiver: 'webhook-notifications'
    groupBy: ['alertname', 'namespace']
    groupWait: 10s
    groupInterval: 5m
    repeatInterval: 4h
  receivers:
    - name: 'webhook-notifications'
      webhookConfigs:
        - url: 'http://webhook-tester.monitoring.svc.cluster.local:8800/11111111-2222-3333-4444-555555555555'
          sendResolved: true