apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: webhook-config
  namespace: monitoring
  labels:
    alertmanager: main
spec:
  route:
    receiver: 'webhook-notifications'
    groupBy: ['alertname', 'namespace']
    groupWait: 10s
    groupInterval: 5m
    repeatInterval: 4h
  receivers:
    - name: 'webhook-notifications'
      webhookConfigs:
        - url: 'http://my-webhook-tester-webhook-tester.monitoring.svc.cluster.local:8800/93688712-485e-40ef-a43f-226257379e47/'
          sendResolved: true